const SET_STATUS_MOBILE_MENU = 'SET_STATUS_MOBILE_MENU';
const SET_STATUS_VERTICAL_MOBILE_MENU = 'SET_STATUS_VERTICAL_MOBILE_MENU';

const SET_MESSAGE = 'SET_MESSAGE';
const CLEAR_MESSAGE = 'CLEAR_MESSAGE';

const AUTH_FETCH_REGISTER_USER = 'AUTH_FETCH_REGISTER_USER';
const AUTH_REGISTER_SUCCESS = 'AUTH_REGISTER_SUCCESS';
const AUTH_REGISTER_ERROR = 'AUTH_REGISTER_ERROR';
const AUTH_FETCH_LOGIN_USER = 'AUTH_FETCH_LOGIN_USER';
const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS';
const AUTH_LOGIN_ERROR = 'AUTH_LOGIN_ERROR';

export default {
    SET_STATUS_MOBILE_MENU,
    SET_STATUS_VERTICAL_MOBILE_MENU,
    AUTH_FETCH_REGISTER_USER,
    AUTH_REGISTER_SUCCESS,
    AUTH_REGISTER_ERROR,
    AUTH_FETCH_LOGIN_USER,
    AUTH_LOGIN_SUCCESS,
    AUTH_LOGIN_ERROR,
    SET_MESSAGE,
    CLEAR_MESSAGE
}
