const SET_STATUS_MOBILE_MENU = 'SET_STATUS_MOBILE_MENU';
const SET_STATUS_VERTICAL_MOBILE_MENU = 'SET_STATUS_VERTICAL_MOBILE_MENU';

const FETCH_REGISTER_USER = 'FETCH_REGISTER_USER';
const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
const REGISTER_USER_ERROR = 'REGISTER_USER_ERROR';

const SET_MESSAGE = 'SET_MESSAGE';
const CLEAR_MESSAGE = 'CLEAR_MESSAGE';

export default {
    SET_STATUS_MOBILE_MENU,
    SET_STATUS_VERTICAL_MOBILE_MENU,
    FETCH_REGISTER_USER,
    REGISTER_USER_SUCCESS,
    REGISTER_USER_ERROR,
    SET_MESSAGE,
    CLEAR_MESSAGE
}
