const SET_STATUS_MOBILE_MENU = 'SET_STATUS_MOBILE_MENU';
const SET_STATUS_VERTICAL_MOBILE_MENU = 'SET_STATUS_VERTICAL_MOBILE_MENU';

export default {
    SET_STATUS_MOBILE_MENU,
    SET_STATUS_VERTICAL_MOBILE_MENU
}
